### PR TITLE
feat: Update CI for FMT/Clippy

### LINKED ISSUE #9: CI: Update FMT/Clippy
Update CI to run rustfmt and clippy on CI.

### PR DESCRIPTION
**Pull request by asr2003**
/claim #9 
Closes #9

### CODE REVIEW

**Comment by asr2003** [comment]
I will resolve conflicts and fix the failing workflows

**Comment by tusharmath** [comment]
Moving to draft to reduce noise and improve CI efficiency. Once you are ready just mark it as "ready to review". Feel free to give a shoutout on the #contributors channel on Discord if you want immediate attention.

**Comment by tusharmath** [comment]
@asr2003 I think you will need to recreate this PR anyways because too much has changed. Closing this one for those reasons.

**Comment by asr2003** [comment]
Ok I will push changes in new PR by fixing clippy issues found in PR

**Pull request closed without merging**
